name: RedfordResearch
favicon: null
layout_spectrum: 0.6013845286797732
typography_spectrum: 0.03474936936981976
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.049600872211158276
  lightness: 0.1872166246175766
  saturation: 0.9036770206876099
  rhythmicContrast: 0.8372188683133572
purpose: []
